import mongoose from 'mongoose';

const days = (n) => new Date(Date.now() + n * 24 * 60 * 60 * 1000);
const id   = () => new mongoose.Types.ObjectId();

export async function seedJobs(db, idMap) {
   const { techcorp, startuphub, fintech } = idMap;

   const techcorpFrontend  = id();
   const techcorpData      = id();
   const techcorpUIUX      = id();
   const techcorpDevOps    = id();
   const startupMarketing  = id();
   const startupContent    = id();
   const startupProduct    = id();
   const startupBizDev     = id();
   const fintechFinance    = id();
   const fintechRisk       = id();
   const fintechBackend    = id();
   const fintechCompliance = id();

   await db.collection('jobs').insertMany([
      {
         _id: techcorpFrontend,
         title: 'Frontend Developer Intern',
         description: 'Build responsive React interfaces for our SaaS dashboard used by 500+ enterprise clients across Thailand and Vietnam.',
         requirements: 'Familiarity with React.js, HTML/CSS. Knowledge of REST APIs is a plus. Must be enrolled in a university programme.',
         location: 'Bangkok, Thailand',
         category: 'Software Development',
         workMode: 'Hybrid',
         duration: '3 months',
         stipend: 12000,
         deadline: days(30),
         company: techcorp,
         isClosed: false,
         createdAt: new Date(),
         updatedAt: new Date(),
      },
      {
         _id: techcorpData,
         title: 'Data Analyst Intern',
         description: 'Analyse product usage data, build dashboards in Looker Studio, and surface insights to the product team weekly.',
         requirements: 'Basic SQL and Excel proficiency. Exposure to Python or R is a bonus.',
         location: 'Bangkok, Thailand',
         category: 'Data Science',
         workMode: 'Remote',
         duration: '3 months',
         stipend: 10000,
         deadline: days(30),
         company: techcorp,
         isClosed: false,
         createdAt: new Date(),
         updatedAt: new Date(),
      },
      {
         _id: techcorpUIUX,
         title: 'UI/UX Design Intern',
         description: 'Design user flows, wireframes, and hi-fi prototypes for new product features alongside our senior design team.',
         requirements: 'Proficiency in Figma. Portfolio of at least 2 completed projects required.',
         location: 'Bangkok, Thailand',
         category: 'Design',
         workMode: 'On-site',
         duration: '2 months',
         stipend: 9000,
         deadline: days(30),
         company: techcorp,
         isClosed: false,
         createdAt: new Date(),
         updatedAt: new Date(),
      },
      {
         _id: techcorpDevOps,
         title: 'DevOps Intern',
         description: 'Assist in maintaining CI/CD pipelines, Kubernetes clusters, and monitoring stacks on AWS.',
         requirements: 'Basic Linux knowledge. Exposure to Docker or cloud services is a plus.',
         location: 'Bangkok, Thailand',
         category: 'Software Development',
         workMode: 'Remote',
         duration: '3 months',
         stipend: 11000,
         deadline: days(30),
         company: techcorp,
         isClosed: true,
         createdAt: new Date(),
         updatedAt: new Date(),
      },
      {
         _id: startupMarketing,
         title: 'Marketing Intern',
         description: 'Plan and execute digital marketing campaigns across Facebook, Instagram, and LINE for startup clients in our accelerator.',
         requirements: 'Interest in digital marketing. Knowledge of Meta Ads Manager is a bonus.',
         location: 'Chiang Mai, Thailand',
         category: 'Marketing',
         workMode: 'Hybrid',
         duration: '3 months',
         stipend: 8000,
         deadline: days(30),
         company: startuphub,
         isClosed: false,
         createdAt: new Date(),
         updatedAt: new Date(),
      },
      {
         _id: startupContent,
         title: 'Content Creator Intern',
         description: 'Create Thai and English content (blogs, social posts, short videos) that drives organic growth for our portfolio startups.',
         requirements: 'Strong written communication in Thai and English. Video editing skills are a plus.',
         location: 'Chiang Mai, Thailand',
         category: 'Marketing',
         workMode: 'Remote',
         duration: '2 months',
         stipend: 7000,
         deadline: days(30),
         company: startuphub,
         isClosed: false,
         createdAt: new Date(),
         updatedAt: new Date(),
      },
      {
         _id: startupProduct,
         title: 'Product Management Intern',
         description: 'Work directly with founders to define roadmaps, write user stories, and coordinate sprint planning for two early-stage products.',
         requirements: 'Understanding of agile/scrum. Strong analytical and communication skills.',
         location: 'Chiang Mai, Thailand',
         category: 'Product',
         workMode: 'Hybrid',
         duration: '3 months',
         stipend: 9500,
         deadline: days(30),
         company: startuphub,
         isClosed: false,
         createdAt: new Date(),
         updatedAt: new Date(),
      },
      {
         _id: startupBizDev,
         title: 'Business Development Intern',
         description: 'Research partnership opportunities, prepare pitch decks, and support deal negotiations with investors and corporates.',
         requirements: 'Business or finance background preferred. Presentation and research skills essential.',
         location: 'Chiang Mai, Thailand',
         category: 'Business',
         workMode: 'On-site',
         duration: '3 months',
         stipend: 8500,
         deadline: days(30),
         company: startuphub,
         isClosed: true,
         createdAt: new Date(),
         updatedAt: new Date(),
      },
      {
         _id: fintechFinance,
         title: 'Finance Intern',
         description: 'Support the finance team with reconciliation, monthly reporting, and regulatory filing preparation for Bank of Thailand submissions.',
         requirements: 'Accounting or finance major. Excel proficiency required. Attention to detail is critical.',
         location: 'Bangkok, Thailand',
         category: 'Finance',
         workMode: 'On-site',
         duration: '4 months',
         stipend: 13000,
         deadline: days(30),
         company: fintech,
         isClosed: false,
         createdAt: new Date(),
         updatedAt: new Date(),
      },
      {
         _id: fintechRisk,
         title: 'Risk Analyst Intern',
         description: 'Assist in building credit scoring models and stress-testing portfolios to comply with ASEAN banking risk standards.',
         requirements: 'Statistics or quantitative finance background. Python or R experience preferred.',
         location: 'Bangkok, Thailand',
         category: 'Finance',
         workMode: 'Hybrid',
         duration: '3 months',
         stipend: 11000,
         deadline: days(30),
         company: fintech,
         isClosed: false,
         createdAt: new Date(),
         updatedAt: new Date(),
      },
      {
         _id: fintechBackend,
         title: 'Backend Developer Intern',
         description: 'Develop and maintain Node.js microservices that process 2M+ daily payment transactions on our core banking platform.',
         requirements: 'Node.js fundamentals. Understanding of REST APIs and databases (SQL or NoSQL).',
         location: 'Bangkok, Thailand',
         category: 'Software Development',
         workMode: 'Remote',
         duration: '3 months',
         stipend: 12500,
         deadline: days(30),
         company: fintech,
         isClosed: false,
         createdAt: new Date(),
         updatedAt: new Date(),
      },
      {
         _id: fintechCompliance,
         title: 'Compliance Intern',
         description: 'Support the legal team in reviewing AML policies, drafting compliance reports, and monitoring regulatory updates from the SEC.',
         requirements: 'Law or finance background. Detail-oriented with strong document drafting skills.',
         location: 'Bangkok, Thailand',
         category: 'Legal',
         workMode: 'On-site',
         duration: '2 months',
         stipend: 9000,
         deadline: days(30),
         company: fintech,
         isClosed: true,
         createdAt: new Date(),
         updatedAt: new Date(),
      },
   ]);

   console.log('✓ jobs: 12 inserted');
   return {
      techcorpFrontend, techcorpData, techcorpUIUX, techcorpDevOps,
      startupMarketing, startupContent, startupProduct, startupBizDev,
      fintechFinance, fintechRisk, fintechBackend, fintechCompliance,
   };
}
